# Generated by Django 4.2.4 on 2023-08-28 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Post Title')),
                ('slug', models.SlugField(default='')),
                ('author', models.CharField(max_length=30, verbose_name='Auther name')),
                ('body', models.CharField(max_length=500, verbose_name='Post body')),
                ('publish', models.DateTimeField(verbose_name='Data of publish')),
                ('created', models.DateTimeField(verbose_name='Data of create')),
                ('updated', models.DateTimeField(verbose_name='Data of last update')),
                ('status', models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=256)),
                ('body', models.CharField(max_length=500, verbose_name='Post body')),
                ('created', models.DateTimeField(verbose_name='Data of create')),
                ('updated', models.DateTimeField(verbose_name='Data of last update')),
                ('isActive', models.BooleanField(verbose_name='is active')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.post')),
            ],
        ),
    ]
