# Generated by Django 4.2.4 on 2023-08-28 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='user_name',
            field=models.CharField(default=datetime.datetime(2023, 8, 28, 13, 59, 38, 221524, tzinfo=datetime.timezone.utc), max_length=50, verbose_name='Author Name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='body',
            field=models.TextField(max_length=500, verbose_name='Comment Body'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 13, 58, 50, 277411, tzinfo=datetime.timezone.utc), verbose_name='Data of create'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=256, verbose_name='Author Email'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isActive',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 13, 58, 50, 277411, tzinfo=datetime.timezone.utc), verbose_name='Data of last update'),
        ),
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(max_length=2000, verbose_name='Post body'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 13, 58, 50, 276440, tzinfo=datetime.timezone.utc), verbose_name='Data of create'),
        ),
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 13, 58, 50, 276440, tzinfo=datetime.timezone.utc), verbose_name='Data of publish'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='P', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 28, 13, 58, 50, 276440, tzinfo=datetime.timezone.utc), verbose_name='Data of last update'),
        ),
    ]
