# Generated by Django 4.2.5 on 2023-09-11 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('posts', '0004_alter_post_body'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warnings_num', models.SmallIntegerField(default=0, verbose_name='Number of Warnings')),
                ('date_of_block', models.DateTimeField(default=None, verbose_name='date of blocked')),
                ('read_posts_num', models.SmallIntegerField(default=0, verbose_name='Number of Warnings')),
                ('day_posts_num', models.SmallIntegerField(default=0, verbose_name='Number of created posts in a day')),
                ('posts_dislikes', models.ManyToManyField(related_name='users_disliked', to='posts.post')),
                ('posts_likes', models.ManyToManyField(related_name='users_liked', to='posts.post')),
                ('subscriptions', models.ManyToManyField(related_name='subscribed_users', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
