# Generated by Django 4.2.5 on 2023-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_body'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracking',
            name='read_posts',
            field=models.ManyToManyField(related_name='read_user', to='posts.post'),
        ),
    ]
