# Generated by Django 4.2.5 on 2023-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usertracking_read_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertracking',
            name='date_of_block',
        ),
        migrations.AddField(
            model_name='usertracking',
            name='date_of_end_block',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date of end block'),
        ),
        migrations.AddField(
            model_name='usertracking',
            name='date_of_start_block',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='date of start block'),
        ),
    ]
