# Generated by Django 4.2.5 on 2023-09-13 12:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_usertracking_date_of_block_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertracking',
            name='allowed_read_post_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='date of last read post'),
        ),
    ]
