# Generated by Django 4.2.5 on 2023-09-14 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_notification_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='is_read',
        ),
    ]
