# Generated by Django 4.2.5 on 2023-09-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_createpostnotification_delete_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpostnotification',
            name='message',
            field=models.TextField(default='null', max_length=200, verbose_name='Text Message'),
            preserve_default=False,
        ),
    ]
